import 'package:flutter/services.dart';

import './models/places.dart';
import './models/category.dart';

const CATEGORIES_DUMMY_DATA = const [
  Category(
    id: 'P1',
    title: 'Tempat Wisata',
    description: 'pantai jogja',
    image:'https://1.bp.blogspot.com/-kcZFQPeHQSQ/YQGnpiXVP6I/AAAAAAAAMvo/AMaTQ54tV2caa1fXIo_9opxFQ3dCo90bgCLcBGAsYHQ/s320/tempat_wisata.png',
  ),
  Category(
    id: 'P2',
    title: 'Penginapan',
    description: '',
    image: 'https://1.bp.blogspot.com/-Gx6HEbOpnyk/YQGnpO-whfI/AAAAAAAAMvg/Q9QrXo9CaBIyEN4se9T3KNxRuhtt8vrvACLcBGAsYHQ/s320/penginapan.png',
  ),
  Category(
    id: 'P3',
    title: 'Tempat Ibadah',
    description: '',
    image: 'https://1.bp.blogspot.com/-J4yvyScVBbk/YQGnpie2eSI/AAAAAAAAMvk/B2imSJevBRoggQtrLmQDeX-r-DevfPLyACLcBGAsYHQ/s320/tempat_ibadah.png',
  ),
  Category(
    id: 'P4',
    title: 'Kuliner',
    description: '',
    image: 'https://1.bp.blogspot.com/-vsYcVMwyZaM/YQGnoOybowI/AAAAAAAAMvQ/IG9dnypDmLgMf8ZvJEr5I0UIZCstdo4rgCLcBGAsYHQ/s320/kuliner.png',
  ),

];


//isi data wisata//

const PLACES_DUMMY_DATA = const [

  //wisata kategori P1 ------------------------------------------------/

  Places(
    id: 'A1',
    name: 'Jalan Malioboro',
    description: 'Jelas saja tempat wisata di Jogja yang satu ini wajib ada di nomor 1. Kamu betul-betul belum ke Jogja namanya kalau enggak mampir atau paling enggak lewat Jalan Malioboro! Selain untuk beli oleh-oleh, kamu juga bisa makan-makan di area Malioboro. Apalagi kalau malam, banyak banget warung tenda berdiri di sini.',
    location: 'malioboro',
    category: 'P1',
    image: 'https://res.klook.com/image/upload/fl_lossy.progressive,q_85/c_fill,w_680/Klook_Noelle_-_Malioboro_Street_Jogja_godrhb.webp',
    price: 2000,
    kontak: 0896230202,
  ),
  Places(
    id: 'A2',
    name: 'Kraton Yogyakarta',
    description: 'Jogja adalah sebuah Daerah Istimewa, yang dipimpin oleh seorang raja yaitu Sultan Hamengkubuwono X. Seorang raja tentu saja butuh istana, dan Kraton Yogyakarta adalah istananya. Sejarah panjang Kesultanan Yogyakarta pun bisa kamu lihat langsung di sini.',
    location: 'Kompleks Utama Kraton Yogyakarta',
    category: 'P1',
    image: 'https://res.klook.com/image/upload/fl_lossy.progressive,q_85/c_fill,w_680/Kraton_Jogja_-_Galih_Yoga_Wicaksono_on_Shutterstock_lnfmdz.webp',
    price: 5000,
    kontak: 08156272728,
  ),
  Places(
    id: 'A3',
    name: 'Alun-Alun Selatan',
    description: 'Alun-Alun Selatan merupakan salah satu Sultans Ground yang, sesuai namanya, terletak di selatan Kraton, namun masih di dalam area Benteng Kraton Yogyakarta. Sedikit berbeda dengan Alun-Alun Utara yang biasanya hanya ramai ketika ada event besar yang digelar, Alun-Alun Selatan selalu ramai hampir setiap harinya. ',
    location: 'Alun-alun Selatan Yogyakarta',
    category: 'P1',
    image: 'https://res.klook.com/image/upload/fl_lossy.progressive,q_85/c_fill,w_680/v1596033262/blog/zsybmiy2wkgcyojadiot.webp',
    price: 5000,
    kontak: 0896230202,
  ),
  Places(
    id: 'A4',
    name: 'Candi Borobudur',
    description: ' Candi Borobudur memang tidak berada di area Yogyakarta, melainkan di Muntilan, Jawa Tengah. Namun candi Buddha terbesar di dunia ini adalah salah satu tempat wisata yang wajib dikunjungi jika kamu sedang liburan ke Jogja! Jaraknya dari pusat kota Jogja adalah sekitar 40km, atau 1,5 jam dengan mengendarai mobil. Enggak terlalu jauh kan?',
    location: 'Yogyakarta',
    category: 'P1',
    image: 'https://res.klook.com/image/upload/fl_lossy.progressive,q_85/c_fill,w_680/foto_Borobudur_f8nmqn.webp',
    price: 20000,
    kontak: 0896230202,
  ),
  Places(
    id: 'A5',
    name: 'Jalan Malioboro',
    description: 'Jelas saja tempat wisata di Jogja yang satu ini wajib ada di nomor 1. Kamu betul-betul belum ke Jogja namanya kalau enggak mampir atau paling enggak lewat Jalan Malioboro! Selain untuk beli oleh-oleh, kamu juga bisa makan-makan di area Malioboro. Apalagi kalau malam, banyak banget warung tenda berdiri di sini.',
    location: 'malioboro',
    category: 'P1',
    image: 'https://res.klook.com/image/upload/fl_lossy.progressive,q_85/c_fill,w_680/Klook_Noelle_-_Malioboro_Street_Jogja_godrhb.webp',
    price: 2000,
    kontak: 0896230202,
  ),
  Places(
    id: 'A6',
    name: 'Kraton Yogyakarta',
    description: 'Jogja adalah sebuah Daerah Istimewa, yang dipimpin oleh seorang raja yaitu Sultan Hamengkubuwono X. Seorang raja tentu saja butuh istana, dan Kraton Yogyakarta adalah istananya. Sejarah panjang Kesultanan Yogyakarta pun bisa kamu lihat langsung di sini.',
    location: 'Kompleks Utama Kraton Yogyakarta',
    category: 'P1',
    image: 'https://res.klook.com/image/upload/fl_lossy.progressive,q_85/c_fill,w_680/Kraton_Jogja_-_Galih_Yoga_Wicaksono_on_Shutterstock_lnfmdz.webp',
    price: 5000,
    kontak: 08156272728,
  ),
  Places(
    id: 'A7',
    name: 'Alun-Alun Selatan',
    description: 'Alun-Alun Selatan merupakan salah satu Sultans Ground yang, sesuai namanya, terletak di selatan Kraton, namun masih di dalam area Benteng Kraton Yogyakarta. Sedikit berbeda dengan Alun-Alun Utara yang biasanya hanya ramai ketika ada event besar yang digelar, Alun-Alun Selatan selalu ramai hampir setiap harinya. ',
    location: 'Alun-alun Selatan Yogyakarta',
    category: 'P1',
    image: 'https://res.klook.com/image/upload/fl_lossy.progressive,q_85/c_fill,w_680/v1596033262/blog/zsybmiy2wkgcyojadiot.webp',
    price: 5000,
    kontak: 0896230202,
  ),
  Places(
    id: 'A8',
    name: 'Candi Borobudur',
    description: ' Candi Borobudur memang tidak berada di area Yogyakarta, melainkan di Muntilan, Jawa Tengah. Namun candi Buddha terbesar di dunia ini adalah salah satu tempat wisata yang wajib dikunjungi jika kamu sedang liburan ke Jogja! Jaraknya dari pusat kota Jogja adalah sekitar 40km, atau 1,5 jam dengan mengendarai mobil. Enggak terlalu jauh kan?',
    location: 'Yogyakarta',
    category: 'P1',
    image: 'https://res.klook.com/image/upload/fl_lossy.progressive,q_85/c_fill,w_680/foto_Borobudur_f8nmqn.webp',
    price: 20000,
    kontak: 0896230202,
  ),
  //B.penginapan kategori P2--------------------------------------------------------------------/

  Places(
      id: 'B2',
      name: 'Ndalem Suryo Saptono Homestay',
      description:'Masing-masing rumah joglo juga dilengkapi teras yang bisa kamu gunakan untuk bersantai sambil menikmati pemandangan kebun. Setiap joglo dihubungkan oleh jalan setapak dan rerumputan yang membuat suasana penginapan semakin asri.' ,
      location: 'Jalan Godean KM 1, Sumberan Baru II No 15',
      category: 'P2',
      price: 2000,
      kontak: 0933434,
      image:'https://ik.imagekit.io/tvlk/blog/2020/01/18513920_1807579656223796_5763787738331480064_n.jpg?tr=dpr-1,w-675' ,
  ),
  Places(
      id: 'B3',
      name: 'Omah Waris Family Guest house',
      description:'Ada berbagai atraksi terdekat yang bisa kamu kunjungi selagi menginap di sini, mulai dari Candi Sambisari yang berjarak sekitar 1,93 km serta Keraton Yogyakarta dan Candi Ratu Boko yang berjarak sekitar 7,5 km dari penginapan. Untuk urusan transportasi kamu tak perlu khawatir, karenaguest housemenyediakan jasa antar-jemput bandara dan layanan sewa kendaraan.' ,
      location: 'Bantul',
      category: 'P2',
      image:'https://imgcy.trivago.com/c_limit,d_dummy.jpeg,f_auto,h_650,q_auto,w_1000/itemimages/38/69/3869420.jpeg' ,
      price: 15000,
    kontak: 0933434,

  ),
  Places(
      id: 'B4',
      name: 'Brothers Inn Babarsari',
      description:'Dengan harga mulai dari Rp250.000, kamu bisa mendapatkan kamar nyaman berfasilitas lengkap di Brothers Inn Babarsari. Selain kasur, setiap kamarnya juga dilengkapi AC, TV, meja, dan kamar mandi. Mengusung desain minimalis, penginapan ini didominasi warna putih dan oranye.' ,
      location: 'Babarsari 47',
      category: 'P2',
      image:'https://ik.imagekit.io/tvlk/blog/2020/01/18513920_1807579656223796_5763787738331480064_n.jpg?tr=dpr-1,w-675' ,
      price: 15000,
    kontak: 0933434,
  ),
  Places(
      id: 'B5',
      name: 'Puri Chorus Hotel',
      description:'Tersedia beberapa tipe kamar yang bisa kamu pilih, yaitu Standard dan Business. Dengan harga sewa mulai dari Rp215.000, kamar yang tersedia dilengkapi fasilitas AC, TV, air panas, dan kamar mandi beserta perlengkapannya. Pihak hotel juga memberikan penawaran khusus bagi tamu yang menginap lebih dari 5 malam, yakni jasa antar-jemput gratis ke bandara maupun stasiun.' ,
      location: 'Samirono Baru 50/55, Gejayan',
      category: 'P2',
      image: 'https://gudeg.net/cni-content/uploads/modules/direktori/logo/thumbs/medium/The%20Cabin%20Hotel.JPG',
      price: 148000,
    kontak: 0933434,
  ),
  Places(
      id: 'B6',
      name: 'Pesona Artha Hostel',
      description:'Penginapan murah di Jogja satu ini cocok bagi parabackpacker.Di Pesona Artha Hotel, kamar yang ditawarkan berupa barak layaknya asrama, karenanya setiap kamar akan diisi lebih dari dua orang. Ada dua jenis kamar yang bisa kamu pilih, yaitu kamar campuran dan kamar khusus wanita. Untuk bermalam di sini, kamu hanya perlu mengeluarkan bujet sebesar Rp95.000– Rp99.000.' ,
      location: 'Jlagran No 7C, Pringgokusuman',
      category: 'P2',
      image: 'https://gudeg.net/cni-content/uploads/modules/direktori/logo/thumbs/medium/Mustokoweni-The-Heritage-Hotel(1).jpg',
      price: 90000-95000,
    kontak: 0933434,
  ),

  Places(
      id: 'B8',
      name: 'EDU Hostel',
      description:'Seluruh kamar yang ada di EDU Hostel memiliki tipe asrama.Penginapan ini akan menjadi akomodasi yang tepat jika kamu berlibur dengan rombongan. Ada beberapa tipe kamar yang ditawarkan, yaitu 6 Bed Female Dormitory, 6 Bed Male Dormitory, dan 4 Bed Private Dormitory.Selain kamar tipe Private Dormitory, kamu harus rela berbagi kamar dengan wisatawan lainnya.' ,
      location: 'Riski',
      category: 'P2',
      image: 'https://gudeg.net/cni-content/uploads/modules/direktori/logo/thumbs/medium/20161019012446.jpeg',
      price: 15000,
    kontak: 0933434,
  ),

  Places(
      id: 'B9',
      name: 'Venezia Homestay & Garden',
      description:'Baiktravelingsendirian atau rombongan, Venezia Homestay & Garden dapat menjadi penginapan yang tepat. Kamar yang disediakan penginapan murah ini berbentuk asrama dengan kasur model tingkat' ,
      location: 'Surami No 55,',
      category: 'P2',
      image: 'https://gudeg.net/cni-content/uploads/modules/direktori/logo/thumbs/medium/20161018030643.jpg',
      price: 180000,
    kontak: 0933434,
  ),

//C.Penginapan P3--------------------------------------------------------------------/
  Places(
    id: 'B10',
    name: 'Masjid Agung (Gede) Kauman',
    description: 'Masjid yang juga dikenal dengan nama Masjid Gede Kauman ini terletak di sebelah barat Alun- Alun Utara yang secara simbolis merupakan transendensi untuk menunjukkan keberadaan Sultan, yaitu di samping pimpinan perang atau penguasa pemerintahan (senopati ing ngalaga), juga sebagai sayidin panatagama khalifatulah (wakil Allah) di dunia di dalam memimpin agama (panatagama) di kasultanan.',
    location: 'Jl. Plataran Kauman Yogyakarta INDONESIA 55133',
    category: 'P3',
    image: 'https://www.gudeg.net/cni-content/uploads/modules/direktori/logo/Masjid-Agung-(Gede)-Kauman.jpg',
    kontak: 62274373622,
  ),
  Places(
    id: 'B11',
    name: 'Masjid Kampus UGM',
    description: 'Masjid Kampus UGM yang terletak di kompleks Masjid Universitas Gajah Mada ini merupakan Masjid kampus terbesar se-Asia Tenggara. Masjid yang menjadi kebanggan khususnya oleh seluruh civitas akademika UGM ini memiliki berbagai keistimewaan. Selain terletak pada wilayah yang luas, bangunan Masjid ini memiliki keindahan arsitektur yang menonjol dan megah.',
    location: 'Kompleks Masjid kampus UGM, Bulaksumur, Depok, Sleman, Yogyakarta.',
    category: 'P3',
    image: 'https://www.gudeg.net/cni-content/uploads/modules/direktori/logo/Maskam-UGM.jpg',
    kontak: 0274564414,
  ),
  Places(
    id: 'C3',
    name: 'Gereja Santo Antonius Kotabaru',
    description: 'Kawasan yang dulu disebut Niuwe Wijk ini mulai berkembang tahun 1920. Situasi itu disebabkan semakin banyak orang Belanda yang menetap di Yogyakarta. Saat itu industri gula, sektor perkebunan dan pendidikan berkembang pesat. Lalu, kawasan di tengah kota ini didesain menjadi tempat yang penuh dengan berbagai fasilitas seperti taman di depan gereja.',
    location: 'Jalan I Dewa Nyoman Oka No. 18 Yogyakarta Indonesia 55224',
    category: 'P3',
    image: 'https://www.gudeg.net/cni-content/uploads/modules/direktori/logo/PP_gereja_santo_antonius.jpg',
    kontak: 0274513975,
  ),
  Places(
    id: 'C4',
    name: 'Vihara Buddha Prabha',
    description: 'Terletak di jalan Brigjen Katamso, bangunan ini berdiri pada tanggal 15 Agustus 1990. Bangunan ini berdiri di atas tanah hibah dari Kraton Yogyakarta pada masa pemerintahan Sri Sultan Hamengku Buwono VII, di mana telah diserahkan pada sejak tahun 1845 yang memang diperuntukkan bagi warga Cina sebagai tempat pemujaan.',
    location: 'Jl. Brigjen Katamso No. 3 Yogyakarta INDONESIA 55121',
    category: 'P3',
    image: 'https://www.gudeg.net/cni-content/uploads/modules/direktori/logo/Vihara-Buddha-Prabha.jpg',
    kontak: 62274378084,
  ),

  Places(
    id: 'C5',
    name: 'Gereja Baciro',
    description: 'Jadwal Perayaan Ekaristi: Misa Harian: Pukul 05.30 WIB Misa Jumat Pertama: Pukul. 05.30 WIB, 17.00 WIB',
    location: 'Jl. Melati Wetan No. 47, Baciro, Yogyakarta 55225',
    category: 'P3',
    image: 'https://www.gudeg.net/cni-content/uploads/modules/direktori/logo/PP_Gereja_Baciro.jpg',
    kontak: 0274564414,
  ),
//D.Penginapan P4--------------------------------------------------------------------/
  Places(
    id: 'D1',
    name: 'Warung Gudeg Bu Lies Yogyakarta',
    description: 'Gudeg Bu Lies merupakan salah satu perusahaan pembuatgudeg bermetode kaleng. Sebuah kemajuan pesat manakala makanan tradisional hanya dapat disajikan langsung. Namun, semenjak pertemuannya dengan salah seorang staff LIPI, semua berubah. Gudeg kini dapat dinikmati dimana saja berada, diluar negeri sekalipun Gudeg kaleng Bu Lies dipasarkan di Singapura dan beberapa negara lain.',
    location: 'Jln.Wijilan No 5 Yogyakarta',
    category: 'P4',
    image: 'https://gudeg.net/cni-content/uploads/modules/direktori/logo/lies1.jpg',
    kontak: 0274450164,
    price: -200000,
  ),
  Places(
    id: 'D2',
    name: 'Soto Seger Mbok Giyem',
    description: 'Menurut penjualnya, banyak pengunjung datang sekitar pukul 12 siang, saat jam makan siang.  Ia menuturkan kekuatan rasa kuah soto Winong ini ada pada kesederhanaan bumbunya. “Kami tidak menggunakan kunir dan bumbu lainnya, “kata pria asal Wonosari, kabupaten Gunung Kidul, Yogyakarta ini. “Hanya bawang merah, bawang putih, garam sama jahe saja.”',
    location: 'Jln Laksda Adisucipto, Kec. DepokSleman, Daerah Istimewa Yogyakarta 55282',
    category: 'P4',
    image: 'https://gudeg.net/cni-content/uploads/modules/direktori/logo/20150914023407.JPG',
    kontak: 085647171626,
    price: -960000,
  ),
  Places(
    id: 'D3',
    name: 'Soto Sedap Boyolali',
    description: 'Kuahnya agak lebih kental. Tidak semua orang cocok dengan karakter kuah soto ala Jogja yang bening dan ringan. Di warung soto pak Marto kuahnya lebih kental dan berwarna kekuningan.',
    location: 'Jln Babarsari, Sleman, Catur Tunggal, Kec. Depok, Kab. Sleman, Daerah Istimewa Yogyakarta 55281',
    category: 'P4',
    image: 'https://gudeg.net/cni-content/uploads/modules/direktori/logo/20160310020814.jpg',
    kontak: 085647171626,
    price: -400000,
  ),
  Places(
    id: 'D4',
    name: 'Angkringan Pendopo nDalem',
    description: 'Lazimnya, angkringan menggunakan gerobak kayu sebagai tempat berjualan. Namun angkringan yang satu ini mengusung konsep yang berbeda. Sesuai namanya Angkringan Pendopo nDalem ini menggunakan pendopo rumah jawa (ruang berukuran besar di bagian depan rumah. Biasanya digunakan untuk menyambut tamu atau acara keluarga) sebagai tempat usaha.',
    location: 'Jalan Sompilan No 12, Ngasem, Yogyakarta',
    category: 'P4',
    image: 'https://gudeg.net/cni-content/uploads/modules/direktori/logo/20160617053430.jpg',
    kontak: 085647171626,
    price: -200000,
  ),
  Places(
    id: 'D5',
    name: 'Sate Kambing Mbah Somorejo',
    description: 'Mblusuk. Saat ini wisata kuliner itu semakin menarik kalau semakin mblusuk. Warung sate kambing mbah Somo, panggilan akrab mbah Somorejo jarang diliput dan diketahui karena lokasinya yang ada di pinggir sawah di daerah Bantul.',
    location: 'Jalan Sompilan No 12, Ngasem, Yogyakarta',
    category: 'P4',
    image: 'https://gudeg.net/cni-content/uploads/modules/direktori/logo/20160129040506.jpg',
    kontak: 085647171626,
    price: -65000,
  ),

  Places(
    id: 'D6',
    name: 'Malioboro Mall',
    description: 'Kuahnya agak lebih kental. Tidak semua orang cocok dengan karakter kuah soto ala Jogja yang bening dan ringan. Di warung soto pak Marto kuahnya lebih kental dan berwarna kekuningan.',
    location: 'Jln Babarsari, Sleman, Catur Tunggal, Kec. Depok, Kab. Sleman, Daerah Istimewa Yogyakarta 55281',
    category: 'P4',
    image: 'https://gudeg.net/cni-content/uploads/modules/direktori/logo/20180711122410.jpg',
    kontak: 085647171626,
    price: -400000,
  ),

];